title: 微信小程序应用开发实验指导
lang: en
description: Write an awesome description for your new site here
author: "张丽"

## local method ##
# theme: jekyll-rtd-theme
# debug:
#   compress: false
#   dist: true
#   shortcodes: true

## remote method ##
remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
